# Generated by Django 5.1.3 on 2024-12-05 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_remove_shopuser_address_address'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'ordering': ['is_default', '-created'], 'verbose_name': 'آدرس', 'verbose_name_plural': 'آدرس ها'},
        ),
        migrations.AddIndex(
            model_name='address',
            index=models.Index(fields=['-created'], name='account_add_created_f5b03b_idx'),
        ),
    ]
