# Generated by Django 5.1.3 on 2024-11-11 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_remove_order_name_order_first_name_order_last_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-created'], 'verbose_name': 'سفارش', 'verbose_name_plural': 'سفارش ها'},
        ),
    ]
